#!/bin/bash
#
# Copyright (c) 2018-2020 Board of Trustees of Leland Stanford Jr. University,
# all rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name of Stanford University shall not
# be used in advertising or otherwise to promote the sale, use or other dealings
# in this Software without prior written authorization from Stanford University.
#

# Fixes the code generated by Swagger Codegen.

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=src/generated/java/org/lockss/laaws/crawler/api/StatusApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.ApiStatus/import org.lockss.util.rest.status.ApiStatus/" $STATUS_API_DELEGATE && rm $STATUS_API_DELEGATE.backup

# Edit StatusApi.java.
STATUS_API=src/generated/java/org/lockss/laaws/crawler/api/StatusApi.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.ApiStatus/import org.lockss.util.rest.status.ApiStatus/" $STATUS_API && rm $STATUS_API.backup

# Edit CrawlsApiDelegate.java.
CRAWLS_API_DELEGATE=src/generated/java/org/lockss/laaws/crawler/api/CrawlsApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.Crawl;/import org.lockss.util.rest.crawler.Crawl;/" $CRAWLS_API_DELEGATE && rm $CRAWLS_API_DELEGATE.backup
sed -i.backup "s/import org.lockss.laaws.crawler.model.CrawlDesc/import org.lockss.util.rest.crawler.CrawlDesc/" $CRAWLS_API_DELEGATE && rm $CRAWLS_API_DELEGATE.backup
sed -i.backup "s/import org.lockss.laaws.crawler.model.Status/import org.lockss.util.rest.crawler.Status/" $CRAWLS_API_DELEGATE && rm $CRAWLS_API_DELEGATE.backup

# Edit CrawlsApi.java.
CRAWLS_API=src/generated/java/org/lockss/laaws/crawler/api/CrawlsApi.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.Crawl;/import org.lockss.util.rest.crawler.Crawl;/" $CRAWLS_API && rm $CRAWLS_API.backup
sed -i.backup "s/import org.lockss.laaws.crawler.model.CrawlDesc/import org.lockss.util.rest.crawler.CrawlDesc/" $CRAWLS_API && rm $CRAWLS_API.backup
sed -i.backup "s/import org.lockss.laaws.crawler.model.Status/import org.lockss.util.rest.crawler.Status/" $CRAWLS_API && rm $CRAWLS_API.backup

# Edit CrawlerStatus.java.
CRAWLER_STATUS=src/generated/java/org/lockss/laaws/crawler/model/CrawlerStatus.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.Status/import org.lockss.util.rest.crawler.Status/" $CRAWLER_STATUS && rm $CRAWLER_STATUS.backup

# Edit CrawlStatus.java.
CRAWL_STATUS=src/generated/java/org/lockss/laaws/crawler/model/CrawlStatus.java
sed -i.backup "s/import org.lockss.laaws.crawler.model.Status/import org.lockss.util.rest.crawler.Status/" $CRAWL_STATUS && rm $CRAWL_STATUS.backup
