#!/bin/bash

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Fixes the code generated by Swagger Codegen.

function fixImport() {
JAVA_SRC=$1
sed -i.backup "s/import $2;/import $3;/" $JAVA_SRC && rm $JAVA_SRC.backup
}

function fixResponseCode1234() {
JAVA_SRC=$1
sed -i.backup 's/responseCode = "1234"/responseCode = "default"/' $JAVA_SRC && rm $JAVA_SRC.backup
}

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=src/generated/java/org/lockss/laaws/crawler/api/StatusApiDelegate.java
fixImport $STATUS_API_DELEGATE org.lockss.laaws.crawler.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit StatusApi.java.
STATUS_API=src/generated/java/org/lockss/laaws/crawler/api/StatusApi.java
fixImport $STATUS_API org.lockss.laaws.crawler.model.ApiStatus org.lockss.util.rest.status.ApiStatus
fixResponseCode1234 $STATUS_API

# Edit CrawlsApiDelegate.java.
CRAWLS_API_DELEGATE=src/generated/java/org/lockss/laaws/crawler/api/CrawlsApiDelegate.java
fixImport $CRAWLS_API_DELEGATE org.lockss.laaws.crawler.model.CrawlDesc org.lockss.util.rest.crawler.CrawlDesc
fixImport $CRAWLS_API_DELEGATE org.lockss.laaws.crawler.model.CrawlJob org.lockss.util.rest.crawler.CrawlJob
fixImport $CRAWLS_API_DELEGATE org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus
fixImport $CRAWLS_API_DELEGATE org.lockss.laaws.poller.model.CrawlWsResult org.lockss.ws.entities.CrawlWsResult

# Edit CrawlsApi.java.
CRAWLS_API=src/generated/java/org/lockss/laaws/crawler/api/CrawlsApi.java
fixImport $CRAWLS_API org.lockss.laaws.crawler.model.CrawlDesc org.lockss.util.rest.crawler.CrawlDesc
fixImport $CRAWLS_API org.lockss.laaws.crawler.model.CrawlJob org.lockss.util.rest.crawler.CrawlJob
fixImport $CRAWLS_API org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus
fixImport $CRAWLS_API org.lockss.laaws.poller.model.CrawlWsResult org.lockss.ws.entities.CrawlWsResult
fixResponseCode1234 $CRAWLS_API

# Edit CrawlStatus.java.
CRAWL_STATUS=src/generated/java/org/lockss/laaws/crawler/model/CrawlStatus.java
fixImport $CRAWL_STATUS org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus

# Edit JobPager
JOB_PAGER=src/generated/java/org/lockss/laaws/crawler/model/JobPager.java
fixImport $JOB_PAGER org.lockss.laaws.crawler.model.CrawlJob org.lockss.util.rest.crawler.CrawlJob
fixImport $JOB_PAGER org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus
fixImport $JOB_PAGER org.lockss.laaws.crawler.model.PageInfo org.lockss.util.rest.repo.model.PageInfo

# Edit JobsApiDelegate.java.
JOBS_API_DELEGATE=src/generated/java/org/lockss/laaws/crawler/api/JobsApiDelegate.java
fixImport $JOBS_API_DELEGATE org.lockss.laaws.crawler.model.CrawlDesc org.lockss.util.rest.crawler.CrawlDesc
fixImport $JOBS_API_DELEGATE org.lockss.laaws.crawler.model.CrawlJob org.lockss.util.rest.crawler.CrawlJob
fixImport $JOBS_API_DELEGATE org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus

# Edit JobsApi.java.
JOBS_API=src/generated/java/org/lockss/laaws/crawler/api/JobsApi.java
fixImport $JOBS_API org.lockss.laaws.crawler.model.CrawlDesc org.lockss.util.rest.crawler.CrawlDesc
fixImport $JOBS_API org.lockss.laaws.crawler.model.CrawlJob org.lockss.util.rest.crawler.CrawlJob
fixImport $JOBS_API org.lockss.laaws.crawler.model.JobStatus org.lockss.util.rest.crawler.JobStatus
fixResponseCode1234 $JOBS_API

# Edit CrawlPager
CRAWL_PAGER=src/generated/java/org/lockss/laaws/crawler/model/CrawlPager.java
fixImport $CRAWL_PAGER org.lockss.laaws.crawler.model.PageInfo org.lockss.util.rest.repo.model.PageInfo

# Edit UrlPager
URL_PAGER=src/generated/java/org/lockss/laaws/crawler/model/UrlPager.java
fixImport $URL_PAGER org.lockss.laaws.crawler.model.PageInfo org.lockss.util.rest.repo.model.PageInfo

# Edit ApiUtils
URL_PAGER=src/generated/java/org/lockss/laaws/crawler/model/UrlPager.java
fixImport $URL_PAGER org.lockss.laaws.crawler.model.PageInfo org.lockss.util.rest.repo.model.PageInfo

# Edit CrawlersApi
CRAWLERS_API=src/generated/java/org/lockss/laaws/crawler/api/CrawlersApi.java
fixResponseCode1234 $CRAWLERS_API

# Edit WsApi
WS_API=src/generated/java/org/lockss/laaws/crawler/api/WsApi.java
fixResponseCode1234 $WS_API
